[package]
name = "servo-fontconfig-sys"
version = "2.11.1"
authors = ["Keith Packard <keithp@keithp.com>", "Patrick Lam <plam@mit.edu>"]
license = "MIT"
description = "Font configuration and customization library"
homepage = "http://fontconfig.org"
repository = "https://github.com/servo/libfontconfig/"

build = "build.rs"

[lib]
name = "fontconfig_sys"
path = "lib.rs"

[dependencies]
expat-sys = "2.1.0"
servo-freetype-sys = "2.4.11"
